In [1]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 2, 3])
c = np.array([10, 20, 30])

d = a + b
e = a - b
f = a * b
g = a / b


In [2]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 2, 3])

c = a + b
d = a - b
e = a * b
f = a / b

g = np.mean(a, axis=0)
h = np.std(a, axis=1)
i = np.var(a)

j = np.sum(a, axis=0)
k = np.prod(a, axis=1)

l = np.cumsum(a)
m = np.cumprod(a)

n = np.dot(a, b)
o = np.cross(a, b)

p = np.transpose(a)
q = np.reshape(a, (1, 9))
r = a.flatten()

s = np.stack((a, b), axis=0)
t = np.vstack((a, b))
u = np.hstack((a, b))

v = np.split(a, 3, axis=0)
w = np.split(a, 3, axis=1)

x = np.where(a > 5, a, 0)
y = np.extract(a > 5, a)

z = np.argsort(b)
aa = np.argmin(a)
ab = np.argmax(a)

ac = np.linalg.det(a)
ad = np.linalg.svd(a)


ValueError: all input arrays must have the same shape

In [ ]:
h = np.mean(a, axis=0)
i = np.std(a, axis=1)
j = np.var(a)


In [ ]:
m = np.cumsum(a)
n = np.cumprod(a)


In [ ]:
k = np.sum(a, axis=0)
l = np.prod(a, axis=1)


In [ ]:
o = np.dot(a, b)
p = np.cross(a[1], b)


In [ ]:
q = np.transpose(a)
r = np.reshape(a, (1, 9))
s = a.flatten()


In [3]:
y = np.where(a > 5, a, 0)
z = np.extract(a > 5, a)


In [4]:
ac = np.min(a)
ad = np.max(a)
ae = np.argmin(a)
af = np.argmax(a)


In [5]:

import numpy as np

# Matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Vectors
v1 = np.array([1, 2])
v2 = np.array([3, 4])

# Matrix multiplication
C = np.dot(A, B)
print("Matrix Multiplication:\n", C)
# [[19 22]
#  [43 50]]

# Dot product of vectors
dot_product = np.dot(v1, v2)
print("Dot Product:", dot_product)
# 11

Matrix Multiplication:
 [[19 22]
 [43 50]]
Dot Product: 11


In [6]:

import numpy as np

# Matrix
A = np.array([[3, 1], [2, 4]])

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
# [4.61803399 2.38196601]
print("Eigenvectors:\n", eigenvectors)
# [[ 0.52573111 -0.85065081]
#  [ 0.85065081  0.52573111]]

Eigenvalues: [2. 5.]
Eigenvectors:
 [[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


In [7]:

import numpy as np

# Matrix
A = np.array([[1, 2], [3, 4], [5, 6]])

# Singular Value Decomposition
U, S, VT = np.linalg.svd(A)
print("U matrix:\n", U)
print("Singular values:", S)
print("VT matrix:\n", VT)

U matrix:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Singular values: [9.52551809 0.51430058]
VT matrix:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [8]:

import numpy as np

# Coefficient matrix
A = np.array([[3, 1], [1, 2]])

# Dependent variable values
b = np.array([9, 8])

# Solve for x
x = np.linalg.solve(A, b)
print("Solution for x:", x)
# [2. 3.]
     

Solution for x: [2. 3.]


In [9]:


import numpy as np

# Matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Vector
v = np.array([1, 0, 1])

# Broadcasting addition
B = A + v
print("Matrix after broadcasting addition:\n", B)
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]]

Matrix after broadcasting addition:
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
