# Introduction to NumPy

NumPy, short for Numerical Python, is a fundamental package for scientific computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures efficiently. NumPy is the backbone of many other scientific libraries in Python, such as SciPy, Pandas, and TensorFlow, making it an essential tool for anyone working in data science, machine learning, or any field involving numerical computations.

## Why Use NumPy?

- **Efficiency**: NumPy arrays are more efficient in terms of both storage and performance compared to traditional Python lists.
- **Functionality**: It offers a wide range of mathematical, logical, shape manipulation, sorting, selecting, I/O, and other operations.
- **Interoperability**: NumPy arrays can interface with a variety of databases, file formats, and other libraries, making data manipulation more streamlined.
- **Community and Ecosystem**: As a widely used library, it has a robust community and extensive documentation, making it easier to find help and resources.

## Key Features of NumPy

- **Ndarray**: A powerful N-dimensional array object.
- **Mathematical Functions**: Comprehensive mathematical functions for operations on arrays.
- **Broadcasting**: Allows operations on arrays of different shapes.
- **Indexing**: Advanced indexing capabilities for array manipulation.
- **Integration**: Tools for integrating C/C++ and Fortran code.

## Installation

Before we dive into using NumPy, we need to install it. If you haven't already installed NumPy, you can do so using pip:

```sh
pip install numpy


## Importing Numpy
To use NumPy in your Python code, you need to import it. It is conventionally imported with the alias np:

In [ ]:
import numpy as np


## Creating Arrays
The core of NumPy is the ndarray object. You can create an array using np.array():

In [1]:
import numpy as np

# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])


## Array Operations
NumPy supports a wide range of operations. Here are a few examples:

### Basic Operations

In [2]:
# Element-wise addition
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # Output: [5 7 9]

# Element-wise multiplication
print(a * b)  # Output: [4 10 18]

# Dot product
print(np.dot(a, b))  # Output: 32


[5 7 9]
[ 4 10 18]
32


## Broadcasting
Broadcasting allows NumPy to perform operations on arrays of different shapes:

In [3]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print(a + b)
# Output:
# [[2 3 4]
#  [3 4 5]
#  [4 5 6]]


[[2 3 4]
 [3 4 5]
 [4 5 6]]


## Array Slicing and Indexing
You can access elements, subarrays, and modify arrays using slicing and indexing:

In [4]:
a = np.array([1, 2, 3, 4, 5])

# Accessing elements
print(a[0])  # Output: 1

# Slicing
print(a[1:4])  # Output: [2 3 4]

# Modifying elements
a[2] = 10
print(a)  # Output: [ 1  2 10  4  5]


1
[2 3 4]
[ 1  2 10  4  5]


## Array Manipulation

NumPy provides a variety of functions to manipulate arrays, allowing for reshaping, flattening, concatenating, stacking, and splitting arrays. These functionalities make it easy to transform data into the desired format for analysis or computation.

### Reshaping Arrays

The `reshape()` function changes the shape of an array without changing its data:

```python
import numpy as np

# Original array
a = np.array([[1, 2, 3], [4, 5, 6]])

# Reshaping to a 3x2 array
reshaped_array = a.reshape((3, 2))
print(reshaped_array)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]


## Flattening Arrays
Flattening an array means converting a multi-dimensional array into a 1D array. This can be done using the flatten() or ravel() functions:

In [5]:
# Flattening the array
flattened_array = a.flatten()
print(flattened_array)
# Output: [1 2 3 4 5 6]

# Using ravel (returns a flattened array, but changes to the raveled array affect the original array)
raveled_array = a.ravel()
print(raveled_array)
# Output: [1 2 3 4 5 6]


[ 1  2 10  4  5]
[ 1  2 10  4  5]


## Concatenating Arrays
The concatenate() function joins two or more arrays along an existing axis:

In [6]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# Concatenating along axis 0
concatenated_array = np.concatenate((a, b), axis=0)
print(concatenated_array)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]


[[1 2]
 [3 4]
 [5 6]]


## Stacking Arrays
Stacking is similar to concatenation, but it joins arrays along a new axis. vstack(), hstack(), and dstack() are commonly used functions:

In [7]:
a = np.array([1, 2])
b = np.array([3, 4])

# Vertical stacking
vstacked_array = np.vstack((a, b))
print(vstacked_array)
# Output:
# [[1 2]
#  [3 4]]

# Horizontal stacking
hstacked_array = np.hstack((a, b))
print(hstacked_array)
# Output: [1 2 3 4]

# Depth stacking
a = np.array([[1], [2]])
b = np.array([[3], [4]])
dstacked_array = np.dstack((a, b))
print(dstacked_array)
# Output:
# [[[1 3]]
#  [[2 4]]]


[[1 2]
 [3 4]]
[1 2 3 4]
[[[1 3]]

 [[2 4]]]


## Splitting Arrays
The split() function splits an array into multiple sub-arrays. You can specify the number of splits or the indices at which to split:

In [8]:
a = np.array([1, 2, 3, 4, 5, 6])

# Splitting into 3 equal sub-arrays
split_array = np.array_split(a, 3)
print(split_array)
# Output: [array([1, 2]), array([3, 4]), array([5, 6])]

# Splitting at specified indices
split_array = np.split(a, [2, 4])
print(split_array)
# Output: [array([1, 2]), array([3, 4]), array([5, 6])]


[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]
